<?php
/**
 * WP-CLI commands for movie export/import.
 *
 * @package RT_Movie_Library
 */

namespace RT_Movie_Library\Classes\Cli;

use RT_Movie_Library\Traits\Singleton;
use RT_Movie_Library\Classes\Cli\Services\Movie_Export_Service;
use RT_Movie_Library\Classes\Cli\Services\Movie_Import_Service;
use RT_Movie_Library\Classes\Cli\Exceptions\Cli_Exception;

defined( 'ABSPATH' ) || exit;

/**
 * Class Movie_Cli_Command
 */
class Movie_Cli_Command extends \WP_CLI_Command {

	use Singleton;

	/**
	 * Constructor.
	 */
	protected function __construct() {
		\WP_CLI::add_command( 'rt-movie', $this );
	}

	/**
	 * Export all rt-movie posts into a CSV file.
	 *
	 * ## OPTIONS
	 *
	 * [--file=<path>]
	 * : Absolute/relative path to output CSV.
	 *
	 * ## EXAMPLES
	 *
	 *     wp rt-movie export --file=wp-content/uploads/rt-movies-export.csv
	 *
	 * @param array<string>         $args Positional args.
	 * @param array<string, string> $assoc_args Assoc args.
	 * @return void
	 */
	public function export( array $args, array $assoc_args ): void {
		$service = new Movie_Export_Service();

		try {
			$result = $service->export_movies( $assoc_args['file'] ?? '' );
		} catch ( Cli_Exception $exception ) {
			\WP_CLI::error( $exception->getMessage() );
		}

		foreach ( $result['warnings'] as $warning ) {
			\WP_CLI::warning( $warning );
		}

		\WP_CLI::success(
			sprintf(
				/* translators: 1: number of exported posts. 2: file path. */
				__( 'Exported %1$d movie posts to %2$s', 'rt-movie-library' ),
				(int) $result['count'],
				(string) $result['path']
			)
		);
	}

	/**
	 * Import movie posts from exported CSV file.
	 *
	 * ## OPTIONS
	 *
	 * --file=<path>
	 * : Path to the CSV file generated by `wp rt-movie export`.
	 *
	 * ## EXAMPLES
	 *
	 *     wp rt-movie import --file=wp-content/uploads/rt-movies-export.csv
	 *
	 * @param array<string>         $args Positional args.
	 * @param array<string, string> $assoc_args Assoc args.
	 * @return void
	 */
	public function import( array $args, array $assoc_args ): void {
		$file_path = trim( $assoc_args['file'] ?? '' );
		if ( '' === $file_path ) {
			\WP_CLI::error( __( 'Missing required --file argument.', 'rt-movie-library' ) );
		}

		$service = new Movie_Import_Service();

		try {
			$result = $service->import_movies( $file_path );
		} catch ( Cli_Exception $exception ) {
			\WP_CLI::error( $exception->getMessage() );
		}

		foreach ( $result['warnings'] as $warning ) {
			\WP_CLI::warning( $warning );
		}

		\WP_CLI::success(
			sprintf(
				/* translators: 1: created count. 2: skipped count. 3: failed count. */
				__( 'Import complete. Created: %1$d, Skipped: %2$d, Failed: %3$d', 'rt-movie-library' ),
				(int) $result['created'],
				(int) $result['skipped'],
				(int) $result['failed']
			)
		);
	}
}
