<?php
/**
 * Meta Sync.
 *
 * A Singleton that hooks into WordPress lifecycle events to:
 *
 *   1. Clean up custom table rows when a Movie or Person post is permanently deleted.
 *   2. Guard the search-results cache bump against autosaves and revisions
 *      (fixes the reported performance bug where saving a draft invalidated
 *       the 5-minute search cache unnecessarily).
 *   3. Invalidate WordPress's own postmeta object cache after a real save,
 *      ensuring that any legacy code still calling get_post_meta() gets fresh data.
 *
 * @package RT_Movie_Library
 */

namespace RT_Movie_Library\Classes\Database;

use RT_Movie_Library\Traits\Singleton;
use WP_Post;

defined( 'ABSPATH' ) || exit;

/**
 * Class Meta_Sync
 *
 * Boot via: Meta_Sync::get_instance();
 */
class Meta_Sync {

	use Singleton;

	/**
	 * Registers all lifecycle hooks.
	 * Protected to enforce Singleton — call get_instance() instead.
	 */
	protected function __construct() {
		// Clean up custom table when a movie/person is permanently deleted.
		add_action( 'before_delete_post', array( $this, 'handle_post_deletion' ) );

		// Guarded cache invalidation — skips autosaves and revisions.
		add_action( 'save_post', array( $this, 'handle_save_post' ), 10, 3 );
	}

	/**
	 * Deletes all custom-table meta rows when a Movie or Person is permanently deleted.
	 *
	 * Hooked to 'before_delete_post' (not 'delete_post') so that
	 * get_post_type() is still reliable — after deletion it returns false.
	 *
	 * @param int $post_id The post being permanently deleted.
	 * @return void
	 */
	public function handle_post_deletion( int $post_id ): void {
		$post_type = get_post_type( $post_id );

		if ( 'rt-movie' === $post_type ) {
			Movie_Meta_Table::delete_all( $post_id );
		} elseif ( 'rt-person' === $post_type ) {
			Person_Meta_Table::delete_all( $post_id );
		}
	}

	/**
	 * Fires on every save_post.
	 * Invalidates caches — but ONLY for real user-initiated saves.
	 *
	 * WHY SKIP AUTOSAVES?
	 *   WordPress auto-saves a draft every 60 seconds in the editor.
	 *   Without this guard, the search-results cache (a 5-minute transient)
	 *   would be invalidated constantly, rendering it useless.
	 *
	 * WHY SKIP REVISIONS?
	 *   Revisions are snapshots of the post. Invalidating the cache for a
	 *   revision would use the revision's ID, not the canonical post ID,
	 *   and the cache would be busted for the wrong post.
	 *
	 * @param int     $post_id Post ID.
	 * @param WP_Post $post    Full post object.
	 * @param bool    $update  True if updating, false if creating.
	 * @return void
	 */
	public function handle_save_post( int $post_id, WP_Post $post, bool $update ): void {
		unset( $update ); // phpcs:ignore Generic.CodeAnalysis.UnusedFunctionParameter.FoundAfterLastUsed -- Required by hook signature.

		if ( wp_is_post_autosave( $post_id ) ) {
			return; // Auto-save — no cache action.
		}

		if ( wp_is_post_revision( $post_id ) ) {
			return; // Revision — no cache action.
		}

		if ( ! in_array( $post->post_type, array( 'rt-movie', 'rt-person' ), true ) ) {
			return; // Not our CPT.
		}

		// Bust WP's own postmeta object cache for this post so that any
		// remaining get_post_meta() calls elsewhere return fresh data.
		wp_cache_delete( $post_id, 'post_meta' );

		// Bump the search results cache version so all search transients
		// built before this save are treated as stale and rebuilt on next request.
		$this->bump_cache_version();
	}

	/**
	 * Increments the cache version option.
	 *
	 * Transient keys generated by the search/block layer embed this version
	 * number. On version change, old keys simply expire and new ones are built.
	 *
	 * @return void
	 */
	private function bump_cache_version(): void {
		$current = (int) get_option( 'rt_search_cache_version', 0 );
		update_option( 'rt_search_cache_version', $current + 1, false );
	}
}
